apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "csv-processor-service"
spec:
  predictor:
    containers:
      - name: csv-processor-container
        image: spy_processor_image:latest  
        command: [ "python" ]
        args: [ "./main.py" ] 
        volumeMounts:
          - name: csv-data
            mountPath: /data  
    volumes:
      - name: csv-data
        persistentVolumeClaim:
          claimName: csv-data-pvc 
